### ISSUE TITLE
Crash at boot

### ISSUE THREAD

**Issue by tacotexmex** [12Me21/screwdriver2#1]
```
ERROR[Main]: ModError: Failed to load and run script from /Users/user/Library/Application Support/minetest/mods/screwdriver2/init.lua:
ERROR[Main]: .../mods/screwdriver2/worldedit.lua:7: attempt to index field '/rotate' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]:    ...mods/screwdriver2/worldedit.lua:7: in main chunk
ERROR[Main]:    [C]: in function 'dofile'
ERROR[Main]:    ...mods/screwdriver2/init.lua:319: in main chunk
```
Not sure why…

**Comment by 12Me21** [comment]
That would happen if it runs before the worldedit commands are created...
Try adding worldedit_commands to the list of optional dependencies in mod.conf. (I can't test now, but that should fix it.)

**Comment by 12Me21** [comment]
It should be fixed now. (It's hard to tell because there's only a 50% chance it'll happen, depending on which mods you're using.)
