### ISSUE TITLE
Add 4dir support

### ISSUE THREAD

**Issue by Wuzzy2** [12Me21/screwdriver2#6]
4dir is a paramtype2 that allows a node to be rotated in one of 4 directions. I suggest that screwdriver2 supports 4dir.

**Comment by 12Me21** [comment]
yes, i will add this.
Also, i see that the default screwdriver does not always call `on_rotate` when rotating a 4dir node.
Are you sure this is a good idea?  This prevents a mod from overriding its left-click (ROTATE_AXIS) behavior on 4dir nodes.
